[package]
name = "markdown-compiler"
version = "0.1.0"
authors = ["PanGan21"]
description = "A basic markdown compiler."
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
<<<<<<< HEAD

[dependencies]
=======
[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.11"
>>>>>>> develop
